---

- name: checksum
  become: false
  delegate_to: localhost
  run_once: true
  block:
    - name: get checksum list
      bodsch.scm.github_checksum:
        project: prometheus-community
        repository: json_exporter
        checksum_file: sha256sums.txt
        user: "{{ lookup('env', 'GH_USER') | default(omit) }}"
        password: "{{ lookup('env', 'GH_TOKEN') | default(omit) }}"
        architecture: "{{ ansible_architecture }}"
        system: "{{ ansible_facts.system }}"
        version: "v{{ json_exporter_version }}"
      register: _latest_checksum

    - name: define checksum for {{ go_arch }} architecture
      ansible.builtin.set_fact:
        __json_exporter_checksum: "{{ _latest_checksum.checksum }}"
      when:
        - _latest_checksum.rc == 0
        - _latest_checksum.checksum is defined
        - _latest_checksum.checksum | string | length > 0

- name: download json_exporter binary archive
  become: false
  delegate_to: "{{ json_exporter_delegate_to }}"
  run_once: "{{ 'false' if json_exporter_direct_download else 'true' }}"
  ansible.builtin.get_url:
    url: "{{ json_exporter_release.download_url }}/download/v{{ json_exporter_version }}/{{ json_exporter_release.file }}"
    dest: "{{ json_exporter_local_tmp_directory }}/{{ json_exporter_release.file }}"
    checksum: "sha256:{{ __json_exporter_checksum }}"
    mode: 0640
  register: _download_archive
  until: _download_archive is succeeded
  retries: 5
  delay: 2
  check_mode: false

- name: extract json_exporter archive
  become: false
  delegate_to: "{{ json_exporter_delegate_to }}"
  run_once: "{{ 'false' if json_exporter_direct_download else 'true' }}"
  ansible.builtin.unarchive:
    src: "{{ json_exporter_local_tmp_directory }}/{{ json_exporter_release.file }}"
    dest: "{{ json_exporter_local_tmp_directory }}/"
    copy: false

...
