---

- name: download json_exporter binary archive
  become: false
  delegate_to: "{{ json_exporter_delegate_to }}"
  run_once: "{{ 'false' if json_exporter_direct_download else 'true' }}"
  ansible.builtin.get_url:
    url: "{{ json_exporter_release.download_url }}/download/v{{ json_exporter_version }}/{{ json_exporter_release.file }}"
    dest: "{{ json_exporter_local_tmp_directory }}/{{ json_exporter_release.file }}"
    mode: 0640
  register: _download_archive
  until: _download_archive is succeeded
  retries: 5
  delay: 2
  check_mode: false

- name: extract json_exporter archive
  become: false
  delegate_to: "{{ json_exporter_delegate_to }}"
  run_once: "{{ 'false' if json_exporter_direct_download else 'true' }}"
  ansible.builtin.unarchive:
    src: "{{ json_exporter_local_tmp_directory }}/{{ json_exporter_release.file }}"
    dest: "{{ json_exporter_local_tmp_directory }}/"
    copy: false

...
