---

- name: detect binary file for json_exporter - '{{ json_exporter_local_tmp_directory }}/json_exporter'
  become: false
  delegate_to: "{{ json_exporter_delegate_to }}"
  run_once: "{{ 'false' if json_exporter_direct_download else 'true' }}"
  ansible.builtin.stat:
    path: "{{ json_exporter_local_tmp_directory }}/json_exporter-{{ json_exporter_version }}.{{ ansible_system | lower }}-{{ system_architecture }}/json_exporter"
  register: stat_file_binary

- name: install json_exporter
  when:
    - stat_file_binary.stat.exists
  block:
    - name: propagate json_exporter binary
      ansible.builtin.copy:
        src: "{{ json_exporter_local_tmp_directory }}/json_exporter-{{ json_exporter_version }}.{{ ansible_system | lower }}-{{ system_architecture }}/json_exporter"
        dest: "{{ json_exporter_install_path }}/json_exporter"
        mode: 0755
        owner: "{{ json_exporter_system_user }}"
        group: "{{ json_exporter_system_group }}"
        remote_src: "{{ 'true' if json_exporter_direct_download else 'false' }}"

    - name: make files executable
      ansible.builtin.file:
        path: "{{ json_exporter_install_path }}/json_exporter"
        mode: 0755
        owner: "{{ json_exporter_system_user }}"
        group: "{{ json_exporter_system_group }}"

    - name: create link to binary
      ansible.builtin.file:
        src: "{{ json_exporter_install_path }}/json_exporter"
        dest: /usr/bin/json_exporter
        state: link
        force: true
        follow: false
      notify:
        - restart json_exporter
  rescue:
    - name: exit with fail
      ansible.builtin.fail:
        msg: "The binary json_exporter was not found!"

- name: create local facts
  ansible.builtin.template:
    src: ansible_facts.j2
    dest: /etc/ansible/facts.d/json_exporter.fact
    mode: 0755

- name: systemd
  when:
    - ansible_service_mgr | lower == "systemd"
  block:
    - name: create systemd service unit
      ansible.builtin.template:
        src: "init/systemd/json_exporter.service.j2"
        dest: "{{ systemd_lib_directory }}/json_exporter.service"
        owner: root
        group: root
        mode: 0644
      notify:
        - daemon-reload
        - restart json_exporter

    - name: create json_exporter run configuration
      ansible.builtin.template:
        src: "json_exporter.j2"
        dest: "{{ json_exporter_defaults_directory }}/json_exporter"
        force: true
        owner: root
        group: "{{ json_exporter_system_group }}"
        mode: 0644
      notify:
        - verify configuration
        - restart json_exporter

...
