---

- name: detect binary file for json_exporter
  become: false
  delegate_to: "{{ json_exporter_delegate_to }}"
  ansible.builtin.stat:
    path: "{{ json_exporter_local_tmp_directory }}/json_exporter-{{ json_exporter_version }}.{{ ansible_system | lower }}-{{ system_architecture }}/json_exporter"
  register: stat_file_binary

- name: fail when extracted binary are missing
  ansible.builtin.fail:
    msg: "missing extracted binary on ansible controller"
  when:
    - not stat_file_binary.stat.exists

- name: propagate json_exporter
  ansible.builtin.copy:
    src: "{{ json_exporter_local_tmp_directory }}/json_exporter-{{ json_exporter_version }}.{{ ansible_system | lower }}-{{ system_architecture }}/json_exporter"
    dest: "{{ json_exporter_install_path }}/json_exporter"
    mode: 0755
    owner: "{{ json_exporter_system_user }}"
    group: "{{ json_exporter_system_group }}"
    remote_src: "{{ 'true' if json_exporter_direct_download else 'false' }}"

- name: make files executable
  ansible.builtin.file:
    path: "{{ json_exporter_install_path }}/json_exporter"
    mode: 0755
    owner: "{{ json_exporter_system_user }}"
    group: "{{ json_exporter_system_group }}"

- name: create link to binary
  ansible.builtin.file:
    src: "{{ json_exporter_install_path }}/json_exporter"
    dest: /usr/bin/json_exporter
    state: link
    force: true
  notify:
    - restart json_exporter

- name: create local facts
  ansible.builtin.template:
    src: ansible_facts.j2
    dest: /etc/ansible/facts.d/alertmanager.fact
    mode: 0755

- name: create the json_exporter systemd service file
  ansible.builtin.template:
    src: systemd/json_exporter.service.j2
    dest: "{{ systemd_lib_directory }}/json_exporter.service"
    owner: root
    group: root
    mode: 0644
  notify:
    - daemon-reload
    - restart json_exporter

...
