---

- name: prepare
  import_tasks: prepare.yaml
  tags:
    - json_exporter_install
    - json_exporter_configure
    - json_exporter_run

- name: download archive
  import_tasks: download.yaml
  tags:
    - json_exporter_install
  when:
    - not stat_json_exporter_binary.stat.exists or
      not stat_json_exporter_binary.stat.path == json_exporter_install_path ~ '/json_exporter'

- name: install
  import_tasks: install.yaml
  tags:
    - json_exporter_install
  when:
    - not stat_json_exporter_binary.stat.exists or
      not stat_json_exporter_binary.stat.path == json_exporter_install_path ~ '/json_exporter'

- name: configure
  import_tasks: configure.yaml
  tags:
    - json_exporter_configure

- name: service
  import_tasks: service.yaml
  tags:
    - json_exporter_run
    - json_exporter_configure

...
