---

- name: include OS specific configuration ({{ ansible_distribution }} ({{ ansible_os_family }}) {{ ansible_distribution_major_version }})
  ansible.builtin.include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      paths:
        - "vars"
      files:
        # eg. debian-10 / ubuntu-20.04 / centos-8 / oraclelinux-8
        - "{{ ansible_distribution | lower }}-{{ ansible_distribution_major_version }}.yml"
        # eg. archlinux-systemd / archlinux-openrc
        - "{{ ansible_distribution | lower }}-{{ ansible_service_mgr | lower }}.yml"
        # eg. debian / ubuntu / centos / oraclelinux
        - "{{ ansible_distribution | lower }}.yml"
        # eg. redhat / debian / archlinux
        - "{{ ansible_os_family | lower }}.yml"
        - default.yaml
      skip: true

- name: update package cache
  ansible.builtin.package:
    update_cache: true

- name: define delegate instance for download handling
  ansible.builtin.set_fact:
    json_exporter_delegate_to: "{{ ansible_host }}"
    json_exporter_local_tmp_directory: "{{
        lookup('env', 'CUSTOM_LOCAL_TMP_DIRECTORY') |
        default('/var/cache/ansible/json_exporter', true) }}/{{ json_exporter_version }}"
  when:
    - json_exporter_direct_download

- name: install dependency
  ansible.builtin.package:
    name: "{{ json_exporter_requirements }}"
    state: present
  when:
    - json_exporter_requirements | default([]) | count > 0

- name: detect installed json_exporter binary
  ansible.builtin.stat:
    path: "{{ json_exporter_install_path }}/json_exporter"
  register: stat_json_exporter_binary

- name: create download directory
  become: false
  delegate_to: "{{ json_exporter_delegate_to }}"
  ansible.builtin.file:
    path: "{{ json_exporter_local_tmp_directory }}"
    state: directory
    mode: 0750

- name: user and group handling
  when:
    - json_exporter_system_user != "root"
  block:
    - name: create json_exporter group
      ansible.builtin.group:
        name: "{{ json_exporter_system_group }}"
        state: present
        system: true

    - name: create json_exporter user
      ansible.builtin.user:
        name: "{{ json_exporter_system_user }}"
        groups: "{{ json_exporter_system_group }}"
        append: true
        shell: /usr/sbin/nologin
        system: true
        createhome: false
        home: /nonexistent

- name: create install directory
  ansible.builtin.file:
    path: "{{ json_exporter_install_path }}"
    state: directory
    owner: "{{ json_exporter_system_user }}"
    group: "{{ json_exporter_system_group }}"
    mode: 0755

- name: create ansible local facts directory
  ansible.builtin.file:
    dest: /etc/ansible/facts.d
    state: directory
    owner: root
    group: root
    mode: 0775

- name: merge json_exporter configuration between defaults and custom
  ansible.builtin.set_fact:
    json_exporter_service: "{{ json_exporter_defaults_service | combine(json_exporter_service, recursive=True) }}"
    json_exporter_release: "{{ json_exporter_defaults_release | combine(json_exporter_release, recursive=True) }}"

...
