---

- name: include OS specific configuration ({{ ansible_distribution }} ({{ ansible_os_family }}) {{ ansible_distribution_major_version }})
  include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      paths:
        - "vars"
      files:
        # eg. debian-10 / ubuntu-20.04 / centos-8 / oraclelinux-8
        - "{{ ansible_distribution | lower }}-{{ ansible_distribution_major_version }}.yml"
        # eg. archlinux-systemd / archlinux-openrc
        - "{{ ansible_distribution | lower }}-{{ ansible_service_mgr | lower }}.yml"
        # eg. debian / ubuntu / centos / oraclelinux
        - "{{ ansible_distribution | lower }}.yml"
        # eg. redhat / debian / archlinux
        - "{{ ansible_os_family | lower }}.yml"
        - default.yaml
      skip: true

- name: update package cache
  package:
    update_cache: true

- name: define delegate instance for download handling
  set_fact:
    json_exporter_delegate_to: "{{ ansible_host }}"
    json_exporter_local_tmp_directory: "{{
        lookup('env', 'CUSTOM_LOCAL_TMP_DIRECTORY') |
        default('/var/cache/ansible/json_exporter', true) }}/{{ json_exporter_version }}"
  when:
    - json_exporter_direct_download

- name: install dependency
  package:
    name: "{{ json_exporter_requirements }}"
    state: present

- name: detect installed json_exporter binary
  stat:
    path: "{{ json_exporter_install_path }}/json_exporter"
  register: stat_json_exporter_binary

- name: create download directory
  become: false
  delegate_to: "{{ json_exporter_delegate_to }}"
  file:
    path: "{{ json_exporter_local_tmp_directory }}"
    state: directory
    mode: 0750
  when:
    - not stat_json_exporter_binary.stat.exists or
      not stat_json_exporter_binary.stat.path == json_exporter_install_path ~ '/json_exporter'

- name: user and group handling
  block:
    - name: create json_exporter group
      group:
        name: "{{ json_exporter_system_group }}"
        state: present
        system: true

    - name: create json_exporter user
      user:
        name: "{{ json_exporter_system_user }}"
        groups: "{{ json_exporter_system_group }}"
        append: true
        shell: /usr/sbin/nologin
        system: true
        createhome: false
        home: /nonexistent
  when:
    - json_exporter_system_user != "root"

- name: create install directory
  file:
    path: "{{ json_exporter_install_path }}"
    state: directory
    owner: "{{ json_exporter_system_user }}"
    group: "{{ json_exporter_system_group }}"
    mode: 0755

- name: fix directory rights for {{ json_exporter_install_path | dirname }}
  file:
    path: "{{ json_exporter_install_path | dirname }}"
    state: directory
    owner: "{{ json_exporter_system_user }}"
    group: "{{ json_exporter_system_group }}"
    mode: 0755
    recurse: true

- name: merge json_exporter release configuration between defaults and custom
  set_fact:
    json_exporter_release: "{{ json_exporter_defaults_release |
      combine( json_exporter_release, recursive=True ) }}"

- name: merge json_exporter logging configuration between defaults and custom
  set_fact:
    json_exporter_logging: "{{ json_exporter_defaults_logging |
      combine( json_exporter_logging, recursive=True ) }}"

- name: merge json_exporter web configuration between defaults and custom
  set_fact:
    json_exporter_web: "{{ json_exporter_defaults_web |
      combine( json_exporter_web, recursive=True ) }}"

# - name: merge json_exporter configuration between defaults and custom
#   set_fact:
#     json_exporter_config: "{{ json_exporter_defaults_config |
#       combine( json_exporter_config, recursive=True ) }}"

...
